const productos = [
    {
        id:1,
        nombre:"Moto",
        desc:"kawasakiZ900",
        precio:5000000,
        img:"src/img/900.jpg",
        cantidad:1
    },
    {
        id:2,
        nombre:"Moto",
        desc:"Indian",
        precio:5000000,
        img:"src/img/1200.jpg",
        cantidad:1
    },
    {
        id:3,
        nombre:"Moto ",
        desc:"Bmw",
        precio:600000,
        img:"src/img/bmw.jpg",
        cantidad:1
    },
    {
        id:4,
        nombre:"harley",
        desc:"Moto",
        precio:7000000,
        img:'src/img/harley.jpg',
        cantidad:1
    },
    {
        id:5,
        nombre:"kawasaki",
        desc:"Moto",
        precio:3000,
        img:"src/img/v900.jpg",
        cantidad:1
    },
]

